pipeline {
    agent any

    environment {
        NODEJS_HOME = tool name: 'nodejs', type: 'NodeJSInstallation'
        PATH = "${NODEJS_HOME}/bin:${env.PATH}"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/rvcarcueva2/pti-web.git'
            }
        }
        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Build') {
            steps {
                sh 'npm run build'
            }
        }
        stage('Deploy') {
            steps {
                // Stop old app (if running)
                sh 'pm2 stop nextjs-app || true'
                // Start new app
                sh 'pm2 start npm --name "nextjs-app" -- start'
            }
        }
    }

    post {
        success {
            mail to: 'reycelvejano24@gmail.com',
                 subject: "✅ Deployment Successful",
                 body: "Your Next.js app was deployed successfully."
        }
        failure {
            mail to: 'reycelvejano24@gmail.com',
                 subject: "❌ Deployment Failed",
                 body: "Check Jenkins logs for errors."
        }
    }
}
